/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modelo;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Diogo
 */
public class tela extends javax.swing.JFrame {

    //CONFIGURAÇÕES
        int tamanhoPopulacao = 100;
        double taxaMutacao = 5;
        double taxaCrossover = 60;
        int iteracao = 30;   // quantidade de crossovers até parar
        int qtd_executado = 10; // quantidade de vezes que reinicia e começa outra vez
        
        // PESOS ATRIBUIDOS
        int lucro = 1, gasto = 1, custoColheita = 1, producaoTotal = 1, producaoCereja = 1;
        
    public tela() {
        initComponents();
        this.campoTamanhoPopulacao.setText(Integer.toString(this.tamanhoPopulacao));
        this.campoTaxaCrossover.setText(Double.toString(this.taxaCrossover));
        this.campoTaxaMutacao.setText(Double.toString(this.taxaMutacao));
        this.campoIteracaoParada.setText(Integer.toString(this.iteracao));
        this.campoRepetir.setText(Integer.toString(this.qtd_executado));
        
        this.pesoLucro.setText(Integer.toString(this.lucro));
        this.pesoGasto_insumo.setText(Integer.toString(this.gasto));
        this.pesoCusto_colheita.setText(Integer.toString(this.custoColheita));
        this.pesoProducao_total.setText(Integer.toString(this.producaoTotal));
        this.pesoProducao_cereja.setText(Integer.toString(this.producaoCereja));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoTamanhoPopulacao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoTaxaCrossover = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoTaxaMutacao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoIteracaoParada = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoRepetir = new javax.swing.JTextField();
        botaoBuscarResultado = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pesoGasto_insumo = new javax.swing.JTextField();
        pesoCusto_colheita = new javax.swing.JTextField();
        pesoProducao_total = new javax.swing.JTextField();
        pesoProducao_cereja = new javax.swing.JTextField();
        pesoLucro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Configurações do Algoritmo");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Tamanho da População (int):");

        campoTamanhoPopulacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Taxa de Crossover (%):");

        campoTaxaCrossover.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Taxa de Mutação (%):");

        campoTaxaMutacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Iterações de parada (int):");

        campoIteracaoParada.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Quatidade a repetir tudo (int):");

        campoRepetir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        botaoBuscarResultado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botaoBuscarResultado.setText("BUSCAR RESULTADO");
        botaoBuscarResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarResultadoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Pesos");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Lucro (MAX):");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Gasto com Insumos (MIN):");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Custo de Colheita (MIN):");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Produção total de café (MAX):");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Produção de Café Cereja (MAX):");

        pesoGasto_insumo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        pesoCusto_colheita.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        pesoProducao_total.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        pesoProducao_cereja.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        pesoLucro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(campoTamanhoPopulacao, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(campoTaxaCrossover, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(campoTaxaMutacao, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(campoIteracaoParada, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(campoRepetir, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(18, 18, 18)
                                    .addComponent(pesoLucro))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(18, 18, 18)
                                    .addComponent(pesoGasto_insumo))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(18, 18, 18)
                                    .addComponent(pesoProducao_total))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(18, 18, 18)
                                    .addComponent(pesoCusto_colheita))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addGap(18, 18, 18)
                                    .addComponent(pesoProducao_cereja, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(botaoBuscarResultado))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel7)))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoTamanhoPopulacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoTaxaCrossover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoTaxaMutacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoIteracaoParada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(campoRepetir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jLabel7)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(pesoLucro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(pesoGasto_insumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(pesoCusto_colheita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(pesoProducao_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(pesoProducao_cereja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(botaoBuscarResultado)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoBuscarResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarResultadoActionPerformed
        
        // RECEBENDO CONFIGURAÇÕES
        this.tamanhoPopulacao = Integer.parseInt(this.campoTamanhoPopulacao.getText());
        this.taxaCrossover = Double.parseDouble(this.campoTaxaCrossover.getText());
        this.taxaMutacao = Double.parseDouble(this.campoTaxaMutacao.getText());
        this.iteracao = Integer.parseInt(this.campoIteracaoParada.getText());
        this.qtd_executado = Integer.parseInt(this.campoRepetir.getText());
        
        // RECEBENDO PESOS
        this.lucro = Integer.parseInt(this.pesoLucro.getText());
        this.gasto = Integer.parseInt(this.pesoGasto_insumo.getText());
        this.custoColheita = Integer.parseInt(this.pesoCusto_colheita.getText());
        this.producaoTotal = Integer.parseInt(this.pesoProducao_total.getText());
        this.producaoCereja = Integer.parseInt(this.pesoProducao_cereja.getText());
        
        
        int x, y, aux = 0;
        ArrayList<Individuo> populacao = new ArrayList<>();
        CrossoverDoisPontos crossover = new CrossoverDoisPontos();
        
        while(aux < qtd_executado){
            
            for(x = 0; x < tamanhoPopulacao; x++){//Gera a população inicial e atribui as aptidões devidas de cada individuo
                Individuo ind = new Individuo();
                ind.aptidao(this.lucro,this.gasto,this.custoColheita,this.producaoTotal,this.producaoCereja);
                populacao.add(ind);
            }
            
            for(y = 1; y <= iteracao; y++){//gera os crossover até a iteração for completada
                populacao = crossover.crossoverDoisPontos(populacao, taxaCrossover, taxaMutacao, this.lucro,this.gasto,this.custoColheita,this.producaoTotal,this.producaoCereja);
            }
            
            System.out.println("ITERAÇÃO: "+(aux+1)+"\n");
            System.out.println("Melhor Individuo (Aptidão): "+populacao.get(0).getAptidao());
            System.out.println("Lucro (L): "+populacao.get(0).L());
            System.out.println("Renda (R): "+populacao.get(0).R());
            System.out.println("Gasto Insumo (G): "+populacao.get(0).G());
            System.out.println("Custo Colheita (C): "+populacao.get(0).C());
            System.out.println("Custo Administrativo (D): "+populacao.get(0).D());
            System.out.println("Custo Beneficiamento (B): "+populacao.get(0).B());
            System.out.println("Produção Café-cereja (E): "+populacao.get(0).E());
            System.out.println("Produção Total (Z): "+populacao.get(0).Z());
            populacao.get(0).adubo();
            populacao.get(0).colheita();
            System.out.println("\n\n");
            
            populacao.clear();
            aux++;
        }
        JOptionPane.showMessageDialog(null, "Confira o resultado no terminal!!!");
    }//GEN-LAST:event_botaoBuscarResultadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoBuscarResultado;
    private javax.swing.JTextField campoIteracaoParada;
    private javax.swing.JTextField campoRepetir;
    private javax.swing.JTextField campoTamanhoPopulacao;
    private javax.swing.JTextField campoTaxaCrossover;
    private javax.swing.JTextField campoTaxaMutacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField pesoCusto_colheita;
    private javax.swing.JTextField pesoGasto_insumo;
    private javax.swing.JTextField pesoLucro;
    private javax.swing.JTextField pesoProducao_cereja;
    private javax.swing.JTextField pesoProducao_total;
    // End of variables declaration//GEN-END:variables
}
